import type { Metadata } from "next";
import { Lato, Oswald, Playfair_Display } from "next/font/google";
import "./globals.css";

const lato = Lato({
  subsets:['latin'],
  weight:['100', '300', '400', '700', '900'],
  variable: '--font-lato'
});

const oswald = Oswald({ subsets: ["latin"], variable: "--font-oswald" });
const playfairDisplay = Playfair_Display({ subsets: ["latin"], variable: "--font-playfair-display" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${lato.variable} ${oswald.variable} ${playfairDisplay.variable}`}>
      <body >{children}</body>
    </html>
  );
}
